baseurl: ""
collections_dir: _collections

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

exclude:
  - .vs
  - _site
  - _styles
  - "*.lock"
  - "*.user"
  - Gemfile
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json

future: true

# Disable incremental build when using Gulp watch function
# incremental: true

kramdown:
  show_warnings: true

port: 8080
title: "&#x16A3 &#x16D5"