baseurl: ""
collections_dir: _collections
destination: ./docs

defaults:
  - scope:
      path: "_assets/images"
    values:
      image: true

exclude:
  - .vs
  - "*.lock"
  - "*.user"
  - docs
  - Gemfile
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md

future: true
incremental: true

kramdown:
  show_warnings: true

port: 8080
timezone: Etc/UTC
title: "&#x16A3 &#x16D5"
url: https://ascenkeeprov.github.io