baseurl: ""
#------------------------------
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
#------------------------------
exclude:
  - .vs
  - "*.lock"
  - "*.njsproj"
  - "*.user"
  - Gemfile
#------------------------------
incremental: true
markdown: kramdown
port: 8080