baseurl: ""
collections_dir: _collections
#------------------------------
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
#------------------------------
exclude:
  - .vs
  - "*.lock"
  - "*.user"
  - Gemfile
#------------------------------
future: true
incremental: true
kramdown:
  show_warnings: true
port: 8080
title: "&#x16A3 &#x16D5"