assets_dir: _assets
author: "Asen Kiprov"
baseurl: ""
collections:
  - certificates
collections_dir: _collections
data_dir: _data
destination: _dist

exclude:
  - .git
  - .github
  - .vs
  - "*.lock"
  - "*.user"
  - docs
  - Gemfile
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - sitemap.xml

future: true

github:
  environment: production
  is_project_page: false
  is_user_page: true
  issues_url: https://github.com/AscenKeeprov/ascenkeeprov.github.io/issues
  license:
    key: mit
    name: MIT License
    spdx_id: MIT
    url: https://api.github.com/licenses/mit
  pages_env: production
  pages_hostname: github.io
  project_tagline: "Asen Kiprov's personal site"
  show_downloads: false

include: ["_pages"]
includes_dir: _includes
incremental: true

keep_files:
  - .git
  - .gitattributes
  - .github
  - .gitignore
  - .vs
  - _config.yml
  - _dist
  - _src
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - sitemap.xml

kramdown:
  input: GFM
  show_warnings: true

layouts_dir: _layouts
pages_dir: _pages
port: 8080
repository: AscenKeeprov/ascenkeeprov.github.io

sass:
  sass_dir: _assets\styles

source: _src
theme: null
timezone: Etc/UTC
title: "Asen Kiprov's personal site"
url: https://ascenkeeprov.github.io/