assets_dir: _assets
baseurl: ""
collections:
  - certificates
collections_dir: _collections
destination: ./docs

exclude:
  - .vs
  - "*.lock"
  - "*.user"
  - docs
  - Gemfile
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  - package-lock.json
  - README.md

future: true

github:
  environment: production
  is_project_page: false
  is_user_page: true
  issues_url: https://github.com/AscenKeeprov/ascenkeeprov.github.io/issues
  license:
    key: mit
    name: MIT License
    spdx_id: MIT
    url: https://api.github.com/licenses/mit
  pages_env: production
  pages_hostname: github.io
  project_tagline: "Asen Kiprov's personal GitHub page."
  show_downloads: false

includes_dir: _includes
incremental: true

kramdown:
  input: GFM
  show_warnings: true

layouts_dir: _layouts
port: 8080
repository: AscenKeeprov/ascenkeeprov.github.io
theme: null
timezone: Etc/UTC
title: "Asen Kiprov"
url: https://ascenkeeprov.github.io